apiVersion: v1
kind: Service
metadata:
  name: data-vent
  namespace: confuse
  labels:
    app: data-vent
    service: export
spec:
  type: ClusterIP
  selector:
    app: data-vent
  ports:
  - name: http
    port: 3040
    targetPort: 3040
    protocol: TCP
