# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import retrieval_pb2 as retrieval__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retrieval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalServiceStub(object):
    """Data-Vent Retrieval Service - intelligent search and graph traversal
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/confuse.retrieval.v1.RetrievalService/Retrieve',
                request_serializer=retrieval__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=retrieval__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/confuse.retrieval.v1.RetrievalService/Search',
                request_serializer=retrieval__pb2.RetrievalSearchRequest.SerializeToString,
                response_deserializer=retrieval__pb2.RetrievalSearchResponse.FromString,
                _registered_method=True)
        self.DFSTraverse = channel.unary_unary(
                '/confuse.retrieval.v1.RetrievalService/DFSTraverse',
                request_serializer=retrieval__pb2.RetrievalDFSRequest.SerializeToString,
                response_deserializer=retrieval__pb2.RetrievalDFSResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/confuse.retrieval.v1.RetrievalService/HybridSearch',
                request_serializer=retrieval__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=retrieval__pb2.HybridSearchResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/confuse.retrieval.v1.RetrievalService/HealthCheck',
                request_serializer=retrieval__pb2.RetrievalHealthRequest.SerializeToString,
                response_deserializer=retrieval__pb2.RetrievalHealthResponse.FromString,
                _registered_method=True)


class RetrievalServiceServicer(object):
    """Data-Vent Retrieval Service - intelligent search and graph traversal
    """

    def Retrieve(self, request, context):
        """Full retrieval pipeline: decompose → parallel search → aggregate
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Vector similarity search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DFSTraverse(self, request, context):
        """DFS traversal from starting chunks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Hybrid search (vector + graph)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=retrieval__pb2.RetrieveRequest.FromString,
                    response_serializer=retrieval__pb2.RetrieveResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=retrieval__pb2.RetrievalSearchRequest.FromString,
                    response_serializer=retrieval__pb2.RetrievalSearchResponse.SerializeToString,
            ),
            'DFSTraverse': grpc.unary_unary_rpc_method_handler(
                    servicer.DFSTraverse,
                    request_deserializer=retrieval__pb2.RetrievalDFSRequest.FromString,
                    response_serializer=retrieval__pb2.RetrievalDFSResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=retrieval__pb2.HybridSearchRequest.FromString,
                    response_serializer=retrieval__pb2.HybridSearchResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=retrieval__pb2.RetrievalHealthRequest.FromString,
                    response_serializer=retrieval__pb2.RetrievalHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'confuse.retrieval.v1.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('confuse.retrieval.v1.RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Data-Vent Retrieval Service - intelligent search and graph traversal
    """

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.retrieval.v1.RetrievalService/Retrieve',
            retrieval__pb2.RetrieveRequest.SerializeToString,
            retrieval__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.retrieval.v1.RetrievalService/Search',
            retrieval__pb2.RetrievalSearchRequest.SerializeToString,
            retrieval__pb2.RetrievalSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DFSTraverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.retrieval.v1.RetrievalService/DFSTraverse',
            retrieval__pb2.RetrievalDFSRequest.SerializeToString,
            retrieval__pb2.RetrievalDFSResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.retrieval.v1.RetrievalService/HybridSearch',
            retrieval__pb2.HybridSearchRequest.SerializeToString,
            retrieval__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/confuse.retrieval.v1.RetrievalService/HealthCheck',
            retrieval__pb2.RetrievalHealthRequest.SerializeToString,
            retrieval__pb2.RetrievalHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
